#!/bin/bash                                                                                                                  
sleep 1                                                                                                                      
if [[ "$1" == "-f" ]] ; then                                                                                                 
        pidToKill=`ps -ef|grep kindle-display.sh|tr -s " "|grep " 1 "|cut -d " " -f 2`                                       
        if [[ $pidToKill -gt 0 ]] ; then                                                                                     
                kill -9 $pidToKill                                                                                           
                sleep 3                                                                                                      
        fi                                                                                                                   
fi                                                                                                                           
                                                                                                                             
isrunning=`ps -ef|grep kindle-display.sh|grep " 1 "|wc -l`                                                                   
if [[ $isrunning -le 0 ]] ; then                                                                                             
  if [[ -f /mnt/us/extensions/tyler/newscript ]] ; then                                                                      
    newscriptcount=$(wc -l /mnt/us/extensions/tyler/newscript|cut -d" " -f1)                                                 
    if [[ $newscriptcount -gt 10 ]] ; then                                                                                   
      mv /mnt/us/extensions/tyler/newscript /mnt/us/extensions/tyler/kindle-display.sh                                       
    fi                                                                                                                       
  fi                                                                                                                         
  /mnt/us/extensions/tyler/kindle-display.sh &                                                                               
fi
